# Generated by Django 2.0.7 on 2018-07-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
