# Generated by Django 2.0.7 on 2018-07-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20180714_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
