# Generated by Django 2.0.7 on 2018-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
