# Generated by Django 2.0.7 on 2018-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20180715_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(blank=True, to='shopapp.ImageModel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
