# Generated by Django 2.0.7 on 2018-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_auto_20180715_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='showup_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
