# Generated by Django 2.0.7 on 2018-07-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_auto_20180717_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('img', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='bar',
            field=models.FloatField(default=0),
        ),
    ]
