# Generated by Django 2.0.7 on 2018-07-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0019_auto_20180718_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproducts', to='shopapp.Product'),
        ),
    ]
