# Generated by Django 2.0.7 on 2018-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0020_auto_20180718_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productincart',
            name='summary',
            field=models.FloatField(default=0),
        ),
    ]
